UART Specification Review
Panduza/pzadev-picoha pull request #1
Opened 2023-10-18 11:20 UTC by XdoctorwhoZ

2023-10-18 11:49 UTC, XdoctorwhoZ reviewed
Premier revue, il faut déjà traiter ces points avant d'avancer

2023-10-18 11:49 UTC, XdoctorwhoZ commented on projects/uart/README.md
> +The serial number of the device **must** be XXXX
Voir Morad, il avait trouvé les infos pour utiliser ces IDs

2023-10-18 11:49 UTC, XdoctorwhoZ commented on projects/uart/README.md
> +| `0x0000`    | `0x00FF`  | Generic requests      |
Je suis pour limiter juste les infos ici à l'adapter UART. la distinction se fera via les ID USB

2023-10-18 11:49 UTC, XdoctorwhoZ commented on projects/uart/README.md
> +The product **must** enable the baud rate configuration
enable the baudrate ? 
Plutot
must provide a way to change and read the baudrate ?
Ensuite tu peux ajouter ici le 'code' qui sera a écrire le baudrate et le code pour lire (ces spécifications vont être très orienté conception)

2023-10-18 11:49 UTC, XdoctorwhoZ commented on projects/uart/README.md
> +The internal LED of the product **must** be turned on during the start and the execution of the firmware
Bonne idée, tu peux aussi faire inverser l'allumage quand tu recois une commande ?

2023-10-18 11:49 UTC, XdoctorwhoZ commented on projects/uart/README.md
> +The internal LED of the product **must** be turned off when the firmware is stopped
Tant que l'adapter est connecté en USB il est allumé donc cette exigence est bizarre

2023-10-18 12:40 UTC, fdmysterious commented on projects/uart/README.md
> +| `0x0000`    | `0x00FF`  | Generic requests      |
@XdoctorwhoZ Dans l'idée que j'avais, les premières commandes sont communes à tous les appareils : Ping, version du SW, _etc._ Par contre, on peut effectivement étudier la piste d'avoir ensuite les codes requêtes de `0x0100` à `0x7FFF` dédiés à chaque interface.

2023-10-27 23:13 UTC, fdmysterious requested changes
Review 2

2023-10-27 23:13 UTC, fdmysterious commented on projects/uart/img/slip.jpg
écrire peut-être un `0xC0` en dessous du `END flag` ?

2023-10-27 23:13 UTC, fdmysterious commented on projects/uart/README.md
> +We chose to use the free shared USB VID/PID instead of the Raspberry Pi VID/PID to assure not to have the product been mistaken with another Raspberry Pi product.
Rediriger peut-être vers la page github de raspberry qui explique les choses.

2023-10-27 23:13 UTC, fdmysterious commented on projects/uart/README.md
> +#### [REQ_1030] USB custom frame
Au lieu de mentionner un `Custom frame`  un peu partout dans le doc, peut-être plus parler du `HA protocol` ?

2023-10-27 23:13 UTC, fdmysterious commented on projects/uart/README.md
> +The product **must** use a custom frame protocol. The frames are composed of:
The product **must** use a custom protocol hereby named the `HA protocol` ?

2023-10-27 23:13 UTC, fdmysterious commented on projects/uart/README.md
> +#### [REQ_1040] Custom frame CRC
HA protocol CRC

2023-10-27 23:13 UTC, fdmysterious commented on projects/uart/README.md
> +The CRC used in USB custom frame **must** be `crc-ccit-false`. It can be implemented in two different ways. By using the predefined:
The CRC used in the HA protocol frame **must** use the standard CRC16 `crc-ccitt-false`. Parameters of this CRC are:

| Parameter    |  Value     |
|:------------:|:----------:|
| Polynom      | `0x1021`     |
| Init         | `0xffff`     |
| Refin        | `false`      |
| Refout       | `false`      |
| Xorout       | `0x0000`     |
| Check        | `0x29b1`     |

Using the `crcmod` python library, it can be instanciated using the following call:

```python
crc16 = crcmod.mkCrcFun(0x11021, rev=False, initCrc=0xFFFF, xorOut=0x0000)
```

Or using its predefined counterpart:

```python
crc16 = crcmod.predefined.mkCrcFun("crc-ccitt-false")
```

2023-10-27 23:13 UTC, fdmysterious commented on projects/uart/README.md
> +#### [REQ_1050] Custom frame transfer machanism
HA protocol transfer mechanism

2023-10-27 23:13 UTC, fdmysterious commented on projects/uart/README.md
> +The product **must** answer when the ping request `0x0000` is received with the good answer `0xFFFF`.
Formattage: mettre ping en code: The product **must** the `Good` (`0xFFFF`) answer when the `Ping` (`0x0000`) request is received.

2023-10-27 23:13 UTC, fdmysterious commented on projects/uart/README.md
> +The product **must** answer when the ItfType request `0x0001` is received with the ItfTypeResp answer `0xFEFE`. The data returned must be `"picoha-uart"`.
Formattage `ItfType` et `ItfTypeResp`. Dans l'idée il faut normalement que la valeur retournée soit une valeur numérique qui permette d'identifier le type d'interface. Mais on peut garder la logique de retourner le product pour l'instant. A discuter.

2023-10-27 23:13 UTC, fdmysterious commented on projects/uart/README.md
> +The product **must** answer when the Version request `0x0002` is received with the VersionResp answer `0xFEFF`. The data returned must be version of the firmware loaded on the product.
Formattage `Version` et `VersionResp`

2023-10-27 23:13 UTC, fdmysterious commented on projects/uart/README.md
> +The product **must** answer when the IdGet request `0x0003` is received with the IdResp answer `0xFEFD`. The data returned must be unique board ID of the product.
Formattage `IdGet`.  Appliquer la même remarque sur les autres items

2023-10-27 23:13 UTC, fdmysterious commented on projects/uart/README.md
> +#### [REQ_2040] Good
ça dépend des requêtes. Peut-être ajouter une clause pour dire que lorsque la requête n'a pas de valeur de retour spécifique, elle renvoie `Good` pour indiquer que l'opération s'est déroulée sans erreur.

2023-10-27 23:13 UTC, fdmysterious commented on projects/uart/README.md
> +The product **must** answer the code `0xFFFE` when a generic error is encountered.
Dans l'idée `Generic error` est actuellement un fourre-tout qui permet d'accompagner l'erreur d'une chaîne de caractère de description. l'idée est de pouvoir indiquer une forme d'erreur "générique", pour que le texte d'erreur soit remontée au PC, si jamais l'erreur n'est pas supportée par un code existant. Après c'est pas forcément quelque chose de super pertinent à faire, puisque le risque est de mettre toutes les erreurs là dedans, et donc de perdre l'interêt des codes d'erreur.

2023-10-27 23:13 UTC, fdmysterious commented on projects/uart/README.md
> +The product **must** answer the code `0xFFFD` when a CRC error is encountered.
The product **must** answer the code `0xFFFD` when the CRC of a received request is invalid.

2023-10-27 23:13 UTC, fdmysterious commented on projects/uart/README.md
> +The product **must** answer the code `0xFFFC` when an unknown code error is encountered.
Il faut dire que c'est lorsque le code de la requête reçue est inconnu

2023-10-27 23:13 UTC, fdmysterious commented on projects/uart/README.md
> +The product **must** answer the code `0xFFFB` when an invalid arguments error is encountered.
Pareil indiquer que c'est lorsque le message reçu n'a pas les bons arguments attendus

2023-10-27 23:13 UTC, fdmysterious commented on projects/uart/README.md
> +The product **must** answer the code `0xFFFA` when a busy error is encountered.
Attention le code `Busy` n'est pas forcément un code d'erreur. C'est un code qui permet di'indiquer simplement qu'une opération est toujours en cours, qu'une ressource n'est pas disponible, etc.

2023-10-27 23:13 UTC, fdmysterious commented on projects/uart/README.md
> +#### [REQ_3000] Send data
Spécifier ce que continent l'argument de la requête.

2023-10-27 23:13 UTC, fdmysterious commented on projects/uart/README.md
> +The product **must** receive data from one other product using UART communication when the command `0x1001` is received.
Pareil spécifier les arguments s'il doit y en avoir

2023-10-27 23:13 UTC, fdmysterious commented on projects/uart/README.md
> +
Indiquer par un tableau quels sont ces baudrates standards. Est-ce d'ailleurs vraiment une bonne idée, si jamais la pico supporte n'importe quel baudrate ? Par exemple, le protocole DMX utilise un baudrate non standard à 250kBauds/s

2023-10-27 23:13 UTC, fdmysterious commented on projects/uart/README.md
> +The product **must** enable hardware flow control.
Pourquoi il ne serait pas configurable ? A priori, s'il n'est pas configurable, il faut bridger les broches RTS/CTS en HW pour les liaisons UART qui n'utilisent pas le flux de contrôle HW (soit la plupart des liaisons courantes).

2023-10-27 23:13 UTC, fdmysterious commented on projects/uart/README.md
> +The product **must** enable the UART communication at the start of the firmware using the default UART settings. The internal LED of the product **must** be turned on at the start of the firmware. Th
Plutôt The LED state **must** be toggled _etc._

2023-10-31 05:10 UTC, merged